config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :users, only: [:index, :new, :show, :create, :update]

  resources :sessions, only: [:new, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :films, except: [:edit, :update]  do
    resources :reviews, except: [:index, :show]
    resources :ratings, except: [:index, :show]
  end

  resources :comments, except: [:index, :show],
                       path: 'reviews/:review_id/comments',
                       as: 'review_comments'
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates_presence_of :title

  scope :most_reviewed, -> { joins(:reviews).group("films.id").order("count(reviews) desc").first }

  scope :most_reviewed_list, -> { joins(:reviews).group("films.id").order("count(reviews) desc") }

  scope :top_five_reviewed, -> { joins(:reviews).group("films.id").order("count(reviews) desc").limit(5) }

  scope :by_category, -> (category) { joins(:category).where("categories.name = ?", category).order("title asc") }

  scope :highest_rated, ->  { all.sort_by(&:average_rating).reverse }

  scope :top_five_rated, ->  { all.sort_by(&:average_rating).reverse.first(5) }

  def average_rating
    if self.ratings.any?
      (self.ratings.reduce(0) { |sum, rating| (sum + rating.stars) } / (self.ratings.count * 1.0)).round(2)
    else
      0
    end

  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authorize, only: :new

  def index
    if params[:filter]
      case params[:filter]
      when 'Highest Rated' then @films = Film.highest_rated
      when 'Top 5 Rated' then @films = Film.top_five_rated
      when 'Most Reviewed' then @films = Film.most_reviewed_list
      when 'Top 5 Reviewed' then @films = Film.top_five_reviewed
      when 'All Films' then @films = Film.all
      else @films = Film.by_category(params[:filter])
      end
    else
      @films = Film.all
    end
  end

  def create
    @film = Film.new(film_params)
    @film.category = Category.find_by(name: category_params[:category])

    respond_to do |format|
      if @film.save
        format.html {redirect_to category_path(@film.category)}
        format.json
      else
        format.html { render action: 'new' }
        format.js { render status: 500 }
        # flash[:errors] = @film.errors.full_messages
        # redirect_to new_film_path
      end
    end
  end

  def new
    @film = Film.new
    respond_to do |format|
      format.html { redirect_to new_film_path }
      format.js
    end
  end

  def show
    @film = Film.find(params[:id])
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    redirect_to root_path
  end

  private
    def film_params
      params.require(:film).permit(:title)
    end

    def category_params
      params.require(:film).permit(:category)
    end
end

app/views/films/_form.html.erb
<div class="container col-md-2 text-center">
  <%= form_for(@film, remote: true) do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title', required: true, autofocus: true %><br>

    <%= f.select :category, Category.all.pluck(:name), {}, { class: 'custom-select' } %><br>

    <br><%= f.submit "Add Film", class: 'btn btn-md btn-primary' %>
  <% end %>
</div>

app/views/films/create.js.erb
<% if @film.errors.any? %>
  <% @film.errors.full_messages.each do |msg| %>
    $('#add_film_div').append("<%= msg %>");
  <% end %>
<% end %>

app/views/films/index.html.erb
<h1 class="film-index">Check Out All These Great Films!</h1>

<h2 class="film-index">All Films</h2>


<div class="drop-down">
  <%= form_tag("/films", method: "get") do %>
    <%= label_tag(:filter, "Filter Options:") %>

    <%= select_tag(:filter, grouped_options_for_select({'Filters' => ['All Films', 'Most Reviewed', 'Highest Rated', 'Top 5 Reviewed', 'Top 5 Rated'], 'By Category' => Category.all.pluck(:name)}), class: "") %>
    <%= submit_tag("Filter") %>
  <% end %>
</div>

<div class="container">
    <div class="row">
      <% @films.each do |film| %>
        <div class="col-lg-3">
            <h3><%= link_to "#{film.title}", film_path(film) %></h3>
            <p>Rating: <%= film.average_rating %></p>
            <p>Reviews: <%= film.reviews.count %></p>
            <p>Category: <%= film.category.name %></p>
        </div>
      <% end %>
    </div>
</div>

app/views/films/new.html.erb
<h1>Add New Film</h1>

<%= render 'form' %>

<% if flash[:errors] %>
  <p><%= flash[:errors][0] %></p>
<% end %>

app/views/films/new.js.erb
$('#add_film_div').html("<%= j (render 'form') %>");

app/views/films/show.html.erb
<h1><%= @film.title %></h1>

<div class="film-show-reviews">

  <div class="container text-center">
    <div class="row">
        <div class="col-lg-6">
          <div class="card card-outline-primary">
            <div class="card-block">
              <h2>Reviews</h2>
              <% if logged_in? && current_user.trusted %>
                <%= link_to "Add New Review", new_film_review_path(@film) %>
              <% end %>
              <%= render @film.reviews %>
            </div>
          </div>
        </div>

        <div class="col-lg-6">
          <div class="card card-outline-primary">
            <div class="card-block">
              <h2>Ratings</h2>
              <% if logged_in? %>
                <%= link_to 'Add New Rating', new_film_rating_path(@film) %>
              <% end %>
              <p>Average Rating - <%= @film.average_rating %> stars</p>
              <ul class="unordered-list-style">
                <% @film.ratings.each do |rating| %>
                  <li><%= rating.stars %> stars - <%= rating.user.username %></li>

                  <% if logged_in? && current_user == rating.user %>

                    <%= link_to "Edit", edit_film_rating_path(@film, rating) %>
                    <%= link_to "Delete", film_rating_path(@film, rating), method: :delete %>

                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
    </div>
<div class="delete-button">
  <% if logged_in? && current_user.trusted %>
    <%= link_to 'Delete Film', film_path(@film), method: :delete, class: "btn btn-sm btn-primary" %>
  <% end %>
</div>
  </div>
</div>