config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :users, only: [:index, :new, :show, :create, :update]

  resources :sessions, only: [:new, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :films, except: [:edit, :update]  do
    resources :reviews, except: [:index, :show]
    resources :ratings, except: [:index, :show]
  end

  resources :comments, except: [:index, :show],
                       path: 'reviews/:review_id/comments',
                       as: 'review_comments'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :films

  validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/views/categories/index.html.erb
<div class="bg">
  <div class="jumbotron text-center">
    <h1>Crabalicious Film Reviews</h1>
  </div>

  <div class="container text-center">
    <h2>All Categories</h2>
  </div>

  <div class="container text-center">
  <div class="container-fluid">
    <%= link_to "All Users", users_path, class: "btn btn-primary" %>
    <%= link_to "All Films", films_path, class: "btn btn-primary" %>
  </div>
    <div class="row">
      <% @categories.each do |category| %>
        <div class="col-md-6">
          <div class="card card-outline-primary">
            <div class="card-block">
              <%= link_to "#{category.name}", category_path(category) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>



<div class="container text-center">
  <% if logged_in? && current_user.trusted %>
  <div id="add_film_div">
    <%= link_to 'Add Film', new_film_path, remote: true, class: "btn btn-primary" %>
  </div>
<% end %>
  <div class="row">
    <% @category.films.each do |film| %>
      <div class="col-md-6">
        <div class="card card-outline-primary">
          <div class="card-block">
            <%= link_to "#{film.title}", film_path(film) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>