config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :users, only: [:index, :new, :show, :create, :update]

  resources :sessions, only: [:new, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :films, except: [:edit, :update]  do
    resources :reviews, except: [:index, :show]
    resources :ratings, except: [:index, :show]
  end

  resources :comments, except: [:index, :show],
                       path: 'reviews/:review_id/comments',
                       as: 'review_comments'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: :new
  def new
    @film = Film.find(params[:film_id])
    @review = Review.new
  end

  def create
    @film = Film.find(params[:film_id])
    @review = @film.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @film
    else
      flash[:errors] = @review.errors.full_messages
      redirect_to new_film_review_path(@film)
    end
  end

  def edit
    @film = Film.find(params[:film_id])
    @review = Review.find(params[:id])
  end

  def update
    @film = Film.find(params[:film_id])
    @review = Review.find(params[:id])
    @review.assign_attributes(review_params)

    if @review.save
      redirect_to @film
    else
      flash[:errors] = @review.errors.full_messages
      redirect_to edit_film_review_path(@film , @review)
    end
  end

  def destroy
    @film = Film.find(params[:film_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @film
  end

  private

  def review_params
    params.require(:review).permit(:title, :body)
  end
end

app/views/reviews/_form.html.erb
<%= form_for [@film, @review] do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>

  <%= f.label :body, "Body" %>
  <%= f.text_area :body %>

  <%= f.submit "Submit" %>
<% end %>

<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

app/views/reviews/_review.html.erb
<h4><%= review.title %></h4>

<p><%= review.body %></p>
<p><%= review.user.username %></p>

<% if logged_in? && current_user == review.user %>

  <%= link_to "Edit", edit_film_review_path(@film, review) %>
  <%= link_to "Delete", film_review_path(@film, review), method: :delete %>

<% end %>

<div style="background-color: lightgray">
  <h5>Comments</h5>

  <% if logged_in? %>

    <%= link_to "Add Comment", new_review_comment_path(review) %>

  <% end %>

  <% review.comments.each do |comment| %>
    <p><%= comment.content %></p>
    <p>by <%= comment.user.username %></p>

    <% if logged_in? && current_user == comment.user %>

      <%= link_to "Edit", edit_review_comment_path(review, comment) %>
      <%= link_to "Delete", review_comment_path(review, comment), method: :delete %>

    <% end %>
  <% end %>

</div>

app/views/reviews/edit.html.erb
<h1>Edit Your Review</h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>Review Form</h1>

<%= render 'form' %>