config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :users, only: [:index, :new, :show, :create, :update]

  resources :sessions, only: [:new, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :films, except: [:edit, :update]  do
    resources :reviews, except: [:index, :show]
    resources :ratings, except: [:index, :show]
  end

  resources :comments, except: [:index, :show],
                       path: 'reviews/:review_id/comments',
                       as: 'review_comments'
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-light bg-faded navbar-left">
  <div class="container col-md-4">
    <% if logged_in? %>
      <%= link_to current_user.username, user_path(current_user) %>
      <%= link_to 'Home', root_path, :class => 'navbar-brand' %>
      <%= link_to "Sign Out", session_path(current_user), method: :delete %>  
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to 'Home', root_path, :class => 'navbar-brand' %>
      <%= link_to "Sign In", new_session_path %>
    <% end %>    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbcClientProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>